### ISSUE TITLE
Expand usage of AFMReader for all file formats...

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#1025]
Currently [`io.LoadScans`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L593) class has its own method to [`io.LoadScans.load_spm()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L632).

However thanks to @SylviaWhittle this functionality exists in [AFMReader](https://github.com/AFM-SPM/AFMReader/) along with support for a number of other file formats.

We should replace the call to [`pySPM.Bruker()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L643) within the `LoadScans.load_spm()` with `AFMReader.spm.load_spm()`.

An example is already in-place in [`io.LoadScans.load_asd()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L738). 

## Tasks

Overall we need to modify or add the following methods with `AFMReader.*`...

- [x] [`io.LoadScans.load_asd()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L738)
- [x] [`io.LoadScans.load_gwy()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L1043)
- [x] [`io.LoadScans.load_ibw()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L759)
- [x] [`io.LoadScans.load_jpk()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L820)
- [x] [`io.LoadScans.load_spm()`](https://github.com/AFM-SPM/TopoStats/blob/42a764ee7dde7440309bef5b146a2876f1e53457/topostats/io.py#L632)
- [x] [`io.LoadScans.load_topostats()`](https://github.com/AFM-SPM/TopoStats/blob/54dea30e16dc1e022e5cbfe1767cf704ab8c7ef3/topostats/io.py#L694)

### Tests

AFMReader has tests in place to check each format can be read. I'd therefore suggest making sure each method returns the correct tuple of `(image, pixel_to_nm_scale)` values.

Perhaps do each task as a separate Pull Request to make it faster to review and approve ([Stacked Pull Request](https://blog.logrocket.com/using-stacked-pull-requests-in-github/) approach can be used if the work is tackled in one block though).

**Comment by ns-rse** [comment]
Closed by #1031
