### ISSUE TITLE
Further refactoring and unittesting of GrainStats

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#141]
#122 has refactored a fair amount of the `GrainStats` class that @SylviaWhittle wrote but there is still a bit more to undertake. This Issue is meant as an epic that covers the tasks required, each will be broken out into its own issue for addressing and worked on in separate branches.

- [ ] #90 Complete refactoring of `filters.py` and `grains.py` to classes.
- [ ] #138 Extract plots to functions in `topostats.plottingfunc`
- [ ] #139 Refactor calculate_aspect_ratio() and add unittests.
- [ ] #140 Unittest and refactor `convex_hull()` and `graham_scan()`.

One thing to be mindful of when doing this is that Numpy arrays are converted to lists. It should however be possible to do everything with numpy arrays since they too can be iterated over.

There are other changes to the calculation of grain statistics which need to be made as discussed in the IAA meeting 2022-05-12.
