### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#532]
In fixing some issues with documentation and making versions available (see #466) @SylviaWhittle noticed some of the API pages are not being built/included correctly.

+ [ ] `topostats.io` is included but the page is empty.
+ [ ] `topostats.logs` is missing.
+ [ ] `topostats.plotting` is missing (added to `index.rst` in #531).
+ [ ] `topostats.processing` is missing.
+ [ ] `topostats.run_topostats` is missing.
+ [ ] `topostats.scars` is missing.
+ [ ] `topostats.theme` is missing (added to `index.rst` in #531).
+ [ ] `topostats.thresholds` is missing (added to `index.rst` in #531).
+ [ ] `topostats.validation` is missing (added to `index.rst` in #531).

Please add details of any other sections of documentation that are not being built correctly.

**Comment by ns-rse** [comment]
This has something to do with the `sphinx-apidoc` stage. The `docs/` directory contains some `.rst` files that have already been generated, but not all. Only those that are already present are built to html.

From [logs](https://github.com/AFM-SPM/TopoStats/actions/runs/4747059053/jobs/8431678399) we can see...

```
Sphinx apidocs generation
  Creating file ./topostats.rst.
  File ./topostats.filters.rst already exists, skipping.
  File ./topostats.grains.rst already exists, skipping.
  File ./topostats.grainstats.rst already exists, skipping.
  File ./topostats.io.rst already exists, skipping.
  Creating file ./topostats.plotting.rst.
  File ./topostats.plottingfuncs.rst already exists, skipping.
  Creating file ./topostats.processing.rst.
  File ./topostats.run_topostats.rst already exists, skipping.
  Creating file ./topostats.scars.rst.
  Creating file ./topostats.theme.rst.
  Creating file ./topostats.thresholds.rst.
  File ./topostats.utils.rst already exists, skipping.
  Creating file ./topostats.validation.rst.
  Creating file ./topostats.logs.rst.
  Creating file ./topostats.logs.logs.rst.
  File ./topostats.tracing.rst already exists, skipping.
  Creating file ./topostats.tracing.dnacurvature.rst.
  Creating file ./topostats.tracing.dnatracing.rst.
  Creating file ./topostats.tracing.skeletonize.rst.
  Creating file ./topostats.tracing.tracingfuncs.rst.
  Creating file ./modules.rst.
```

Then under Sphinx document generation we see...

```
Sphinx docs compilation
123
  Running Sphinx v6.1.3
124
  WARNING: html_static_path entry '_static' does not exist
125
  myst v1.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
126
  [autosummary] generating autosummary for: configuration.md, contributing.md, data_dictionary.md, faq.md, glossary.md, index.rst, installation.md, introduction.md, notebooks.md, related_software.md, topostats.filters.rst, topostats.grains.rst, topostats.grainstats.rst, topostats.io.rst, topostats.plottingfuncs.rst, topostats.run_topostats.rst, topostats.tracing.rst, topostats.utils.rst, usage.md, workflow.md
```

Need to investigate why the ones that are created aren't included. :thinking:
