### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#638]
+ Useful and help Masters students but not in their current state. Sylvia - we have a decent number of people using
  notebooks, three people have been helped and Notebooks are why they wanted to use them. Two of the issues were trivial
  (lack of coding knowledge), one from them being broken. Probably more people have used them and were successful.
+ Have regular sessions (monthly/quarterly) for people to run TopoStats Hackathon/help class TopoTime.
+ Need to encourage people to get on board with using Notebooks and using Python
+ Notebooks will be a way in for Masters students to learn.

## Actions/Issues to create
  1. [ ] Tests for Notebooks (see [Pytest Notebooks](https://pypi.org/project/pytest_notebook/) - for testing the notebooks run in.
  2. [ ] Run notebooks in Google Colab/JupyterLite
  3. [ ] Notebook for DNA Tracing
